def change():
    print("Ingresar gasto:")
    gasto =float(input())
    print("Dinero recibido")
    entrada=int(input())
    vuelto=(entrada-gasto)
    print()
    print("Vuelto")
    print()
    print("Pesos:")
    print(int(vuelto))
    print("Centavos:")
    print(int((vuelto-(int(vuelto)))*100))
